//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.13 at 06:43:01 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pad.polito.it/fdsBoarding")
package it.polito.dp2.FDS.sol4.jaxb.fdsboarding;
